name: Release
on: [push]
jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          stable: 'true'
          go-version: '^1.17'
      - name: Install mocks generator
        run: go install github.com/vektra/mockery/v2@latest
      - name: Install swagger generator
        run: go install github.com/swaggo/swag/cmd/swag@latest
      - run: go mod download
      - run: go mod verify
      - name: Run Go generate
        run: make generate
      - name: Generate swagger docs
        run: make swagger
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.44.0
          skip-go-installation: true
          skip-pkg-cache: true
          args: -v -c ./build/golangci.yml
  testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          stable: 'true'
          go-version: '^1.17'
      - name: Install mocks generator
        run: go install github.com/vektra/mockery/v2@latest
      - name: Install swagger generator
        run: go install github.com/swaggo/swag/cmd/swag@latest
      - run: go mod download
      - run: go mod verify
      - name: Run Go generate
        run: make generate
      - name: Generate swagger docs
        run: make swagger
      - name: Run tests
        run: make test
  push_to_registry:
    needs: ["linting", "testing"]
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: batyachelly/go_board_back

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: build/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}